import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'surface-dim': '#d2d9f4',
        'secondary-fixed': '#6ffbbe',
        'surface-variant': '#dae2fd',
        'primary': '#3525cd',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#3323cc',
        'on-surface-variant': '#464555',
        'surface-bright': '#faf8ff',
        'on-background': '#131b2e',
        'on-tertiary-fixed-variant': '#004c6e',
        'tertiary-fixed-dim': '#89ceff',
        'primary-fixed-dim': '#c3c0ff',
        'on-secondary-fixed': '#002113',
        'tertiary': '#004d70',
        'surface-container-highest': '#dae2fd',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#b8e0ff',
        'tertiary-fixed': '#c9e6ff',
        'surface-container-high': '#e2e7ff',
        'tertiary-container': '#006693',
        'on-primary-container': '#dad7ff',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#001e2f',
        'error': '#ba1a1a',
        'surface-tint': '#4d44e3',
        'surface-container': '#eaedff',
        'outline': '#777587',
        'on-error-container': '#93000a',
        'surface': '#faf8ff',
        'surface-container-low': '#f2f3ff',
        'on-secondary-container': '#00714d',
        'on-secondary-fixed-variant': '#005236',
        'secondary-container': '#6cf8bb',
        'primary-fixed': '#e2dfff',
        'inverse-primary': '#c3c0ff',
        'on-surface': '#131b2e',
        'primary-container': '#4f46e5',
        'background': '#faf8ff',
        'secondary': '#006c49',
        'inverse-on-surface': '#eef0ff',
        'secondary-fixed-dim': '#4edea3',
        'inverse-surface': '#283044',
        'outline-variant': '#c7c4d8',
        'on-primary-fixed': '#0f0069',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'space-3xs': '0.125rem',
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'margin-mobile': '1rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
      },
      fontFamily: {
        'display-hero': ['Plus Jakarta Sans', 'sans-serif'],
        'display-hero-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['3.5rem', { lineHeight: '4.25rem', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-hero-mobile': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.025em', fontWeight: '800' }],
        'headline-xl': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.5rem', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'label-lg': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-caps': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.08em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
